Description: "SageMaker notebook to predict flight delays"
Resources:
    NotebookInstance:
        Type: "AWS::SageMaker::NotebookInstance"
        Properties:
            InstanceType: "ml.t2.medium"
            RoleArn: !GetAtt ExecutionRole.Arn
            DefaultCodeRepository: "https://github.com/cloudacademy/sagemaker-flight-delays.git"
            NotebookInstanceName: ca-lab-notebook
            VolumeSizeInGB: 5
    ExecutionRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: "Allow"
                      Principal:
                          Service:
                              - "sagemaker.amazonaws.com"
                      Action:
                          - "sts:AssumeRole"
            Path: "/"
            Policies:
                - PolicyName: "root"
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: "Allow"
                            Action:
                                - "s3:GetObject"
                                - "s3:PutObject"
                                - "s3:DeleteObject"
                                - "s3:ListBucket"
                            Resource: "arn:aws:s3:::*"
                          - Effect: "Allow"
                            Action:
                                - "sagemaker:Describe*"
                                - "sagemaker:List*"
                                - "sagemaker:CreatePresignedDomainUrl"
                                - "sagemaker:*App"
                            Resource: "*"
                          - Effect: "Allow"
                            Action:
                            - "elasticfilesystem:CreateMountTarget"
                            - "elasticfilesystem:DeleteFileSystem"
                            - "elasticfilesystem:DeleteMountTarget"
                            Resource: "*"
                            Condition":
                                StringLike: 
                                    aws:ResourceTag/ManagedByAmazonSageMakerResource: "*"
                          - Effect: "Allow"
                            Action:
                                - "elasticfilesystem:DescribeFileSystems"
                                - "elasticfilesystem:DescribeMountTargets"
                            Resource: "*"
                          - Effect: "Allow"
                            Action:
                                - "ec2:CreateTags"
                                - "elasticfilesystem:DescribeMountTargets"
                            Resource:
                                - "arn:aws:ec2:*:*:network-interface/*"
                                - "arn:aws:ec2:*:*:security-group/*"
                          - Effect: "Allow"
                            Action:
                                - "ec2:CreateNetworkInterface"
                                - "ec2:CreateSecurityGroup"
                                - "ec2:DeleteNetworkInterface"
                                - "ec2:DescribeNetworkInterfaces"
                                - "ec2:DescribeSecurityGroups"
                                - "ec2:DescribeSubnets"
                                - "ec2:ModifyNetworkInterfaceAttribute"
                            Resource: "*"
                          - Effect: "Allow"
                            Action:
                                - "ec2:AuthorizeSecurityGroupEgress"
                                - "ec2:AuthorizeSecurityGroupIngress"
                                - "ec2:CreateNetworkInterfacePermission"
                                - "ec2:DeleteSecurityGroup"
                                - "ec2:RevokeSecurityGroupEgress"
                                - "ec2:RevokeSecurityGroupIngress"
                            Resource: "*"
                            Condition":
                                StringLike: 
                                    ec2:ResourceTag/ManagedByAmazonSageMakerResource: "*"
                          - Effect: "Allow"
                            Action:
                                - "sagemaker:CreateUserProfile"
                                - "sagemaker:DescribeUserProfile"
                            Resource: "*"
Outputs:
    NotebookInstanceId:
        Value: !Ref NotebookInstance
